config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#index'

  get '/index', to: 'static_pages#index'

  get '/about', to: 'static_pages#about'

  get '/resume', to: 'static_pages#resume'

  get '/publications', to: 'static_pages#publications'

  get '/contact', to: 'static_pages#contact'

  get '/projects', to: 'static_pages#projects'

  get '/designs', to: 'static_pages#designs'

  get '/leadership', to: 'static_pages#leadership'

  get '/hackathons', to: 'static_pages#hackathons'

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end

  def resume
  end

  def leadership
  end

  def projects
  end

  def designs
  end

  def publications
  end

  def contact
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.haml
#footer
  %link{:href => "//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css", :rel => "stylesheet"}
  %br
    .footerLinks
      %img{:src => "assets/self-bw-1.png", :id => "footerPic"}
      .footerMiddle
        %b Email //
        fayehcheng(at)gmail.com
        %p
          %b LinkedIn //
          linkedin.com/in/fayehcheng
        %b GitHub //
        github.com/fhcheng
        %p
          %b HackerRank //
          hackerrank.com/fhcheng
      .text-right.right-block
        %a{:href => "https://www.linkedin.com/in/fayehcheng", :target => "_blank"}
          %i.fa.fa-linkedin-square.fa-3x.social
        %a{:href => "https://github.com/fhcheng", :target => "_blank"}
          %i.fa.fa-github-square.fa-3x.social
        %a{:href => "https://bitbucket.org/fhcheng/", :target => "_blank"}
          %i.fa.fa-bitbucket-square.fa-3x.social
        %a{:href => "https://twitter.com/fayehcheng", :target => "_blank"}
          %i.fa.fa-twitter-square.fa-3x.social
        %a{:href => "mailto:fayehcheng@gmail.com", :target => "_blank"}
          %i.fa.fa-envelope-square.fa-3x.social
        %br
        .copyright
          Copyright &copy; 2016 Faye Cheng

app/views/layouts/_header.html.haml
#header
%header.navbar.navbar-fixed-top.navbar-inner
  .container
    %nav
      %ul.nav.navbar-nav.center
        %a{:href => index_path} 
          %img{:alt => "", :src => "assets/about1.png", :id => "navLogo"}
        %li= link_to "ABOUT",   about_path
        %li= link_to "PROJECTS",   projects_path
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            PORTFOLIO
            %b.caret
          %ul.dropdown-menu
            %li
              %a{:href => publications_path} Publications
            %li.divider
            %li
              %a{:href => designs_path} Graphic Design
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            RESUME
            %b.caret
          %ul.dropdown-menu
            %li
            %li
              %a{:href => resume_path} Software Engineering
            %li.divider
            %li
              %a{:href => leadership_path} Leadership Involvements
        %li= link_to "CONTACT", contact_path

app/views/layouts/_i2share1.html.haml
.projectsTop
	#carousel1.carousel.slide.carousel-fade{"data-ride" => "carousel"}
		%ol.carousel-indicators
			%li.active{"data-slide-to" => "0", "data-target" => "#carousel1"}
			%li{"data-slide-to" => "1", "data-target" => "#carousel1"}
			%li{"data-slide-to" => "2", "data-target" => "#carousel1"}
		.carousel-inner
			.active.item
				%img{:src => "assets/i2share.png", :id => "i2share_1"}
			.item
				%img{:src => "assets/createProject1.png", :id => "i2share_2"}
			.item
				%img{:src => "assets/myProfile.png", :id => "i2share_3"}
		%a.carousel-control.left{"data-slide" => "prev", :href => "#carousel1"} ‹
		%a.carousel-control.right{"data-slide" => "next", :href => "#carousel1"} ›
	.projectDetails
		%h1 i2share
		%h2 Project Sharing Start-up
		
		.projectTable
			%table
				%tr
					%td
						%b Role:
					%td
						%b Lead Front-end Developer
				%tr
					%td
						%b Website:
					%td
						%a{:href => "http://www.i2share.com", :target => "_blank"} www.i2share.com
						(not yet launched)
				%tr
					%td
						%b Status:
					%td Currently in production
				%tr
					%td
						%b Tools:
					%td Ruby on Rails, HTML/CSS, Javascript, Bootstrap, Vagrant, Chef, Git, Bitbucket
%br
	.projectDescription
		%h3 Description
		%p I am the primary front-end developer for the start-up, i2share. As a team of 4, we worked to develop our product concept and implement our Rails App using a vagrant environment and git for version control. We held weekly scrum meetings to discuss progress and upcoming tasks, and user testing to guide our design and development. I also worked closely with the back-end team.
		%h3 Product
		%p i2share is a platform that allows users to easily share their personal projects with each other, with the ability to clone and contribute content to make it their own. We specialize in giving users the opportunity to upload Python game projects.
			

app/views/layouts/_lilypad1.html.haml
.projectsTop
	#carousel3.carousel.slide.carousel-fade{"data-ride" => "carousel"}
		%ol.carousel-indicators
			%li.active{"data-slide-to" => "0", "data-target" => "#carousel3"}
			%li{"data-slide-to" => "1", "data-target" => "#carousel3"}
			%li{"data-slide-to" => "2", "data-target" => "#carousel3"}
		.carousel-inner
			.active.item
				%img{:src => "assets/lilypad1.png", :id => "lilypad_1"}
			.item
				%img{:src => "assets/lilypad2.png", :id => "lilypad_2"}
			.item
				%img{:src => "assets/lilypad3.png", :id => "lilypad_3"}
		%a.carousel-control.left{"data-slide" => "prev", :href => "#carousel3"} ‹
		%a.carousel-control.right{"data-slide" => "next", :href => "#carousel3"} ›

	.projectDetails
		%h1 LilyPad
		%h2 Spectra Hackathon 2016
		
		.projectTable
			%table
				%tr
					%td
						%b Role:
					%td
						%b Full-stack Programmer, Product Leader
				%tr
					%td
						%b Website:
					%td
						%a{:href => "http://devpost.com/software/spectra16", :target => "_blank"} http://devpost.com/software/spectra16
				%tr
					%td
						%b Status:
					%td Summer 2016
				%tr
					%td
						%b Tools:
					%td Youtube API, Python, Flask, HTML/CSS, Bootstrap

%br
	.projectDescription
		%h3 Description
		%p A participant of the first annual Spectra Hackathon held at Youtube HQ, I worked on a team of 5 to implement LilyPad. As the Product Leader, I helped my team organize our workflow and lead scrum meetings throughout the hackathon. I created the write-up for our project on DevPost, and was responsibile for our pitch and demo. I also contributed to the development of our python web app.
		%h3 Product
		%p Our team was inspired by Youtube's API to create an interactive platform where videos, like on Youtube, would give us an added layer of authenticity and connectivity for our users. LilyPad is a roommate matching service that pairs compatible users based on unique search criteria which connects them to our library of videos uploaded to LilyPad.

app/views/layouts/_pinkThink1.html.haml
.projectsTop
	#carousel2.carousel.slide.carousel-fade{"data-ride" => "carousel"}
		%ol.carousel-indicators
			%li.active{"data-slide-to" => "0", "data-target" => "#carousel2"}
			%li{"data-slide-to" => "1", "data-target" => "#carousel2"}
			%li{"data-slide-to" => "2", "data-target" => "#carousel2"}
		.carousel-inner
			.active.item
				%img{:src => "assets/pinkthink.png", :id => "pinkThink_1"}
			.item
				%img{:src => "assets/pinkthink2.png", :id => "pinkThink_2"}
			.item
				%img{:src => "assets/pinkthink3.png", :id => "pinkThink_3"}
		%a.carousel-control.left{"data-slide" => "prev", :href => "#carousel2"} ‹
		%a.carousel-control.right{"data-slide" => "next", :href => "#carousel2"} ›

	.projectDetails
		%h1 PinkThink
		%h2 Hackathon Winner 2015
		
		.projectTable
			%table
				%tr
					%td
						%b Role:
					%td
						%b Product Leader, UX & Graphic Designer
				%tr
					%td
						%b Website:
					%td
						%a{:href => "http://devpost.com/software/p-uhdkis", :target => "_blank"} devpost.com/software/p-uhdkis
				%tr
					%td
						%b Awards:
					%td Judge's Choice, Best PinkThink Hack
				%tr
					%td
						%b Tools:
					%td HTML/CSS, Javascript, Arduino, Canva, Python, Photoshop

%br
	.projectDescription
		%h3 Description
		%p I was sponsored by the Anita Borg Institute to attend the Qualcomm EmpowHERment Summit Hackathon in San Diego, CA. With just one year of programming under my belt, this event was a significant milestone for me. Our team of 4 created an interactive web platform for the non-profit PinkThink. As the Product Leader, I helped shape our team's product and developed business ideas that the PinkThink Founder incorporated in their official indigogo campaign.
		%h3 Product
		%p Our platform fully integrates an Arduino-based block coding editor in order to work fully with the back end hardware for the PinkThink bracelet. I came up with the idea to incorporate "code stories" where users would interact with their programmable bracelet by following code challenges to advance. Our thoughtful approach to product development helped us win two hackathon awards, and it was here that I solidified my decision to transition into Computer Science. You can read more about this experience in my Publications page!

app/views/layouts/_platina1.html.haml
.projectsTop
	#carousel4.carousel.slide.carousel-fade{"data-ride" => "carousel"}
		%ol.carousel-indicators
			%li.active{"data-slide-to" => "0", "data-target" => "#carousel4"}
			%li{"data-slide-to" => "1", "data-target" => "#carousel4"}
			%li{"data-slide-to" => "2", "data-target" => "#carousel4"}
		.carousel-inner
			.active.item
				%img{:src => "assets/platina.png", :id => "platina_1"}
			.item
				%img{:src => "assets/platina2.png", :id => "platina_2"}
			.item
				%img{:src => "assets/platina3.png", :id => "platina_3"}
		%a.carousel-control.left{"data-slide" => "prev", :href => "#carousel4"} ‹
		%a.carousel-control.right{"data-slide" => "next", :href => "#carousel4"} ›

	.projectDetails
		%h1 Platina
		%h2 Education Group
		.projectTable
			%table
				%tr
					%td
						%b Role:
					%td
						%b Product Manager, Front-end Developer
				%tr
					%td
						%b Website:
					%td
						%a{:href => "http://platina-education.com", :target => "_blank"} platina-education.com
						(not yet launched)
				%tr
					%td
						%b Status:
					%td Submitted - Software Engineering project
				%tr
					%td
						%b Tools:
					%td Ruby on Rails, Bootstrap, HTML/CSS, Javascript, Git, Heroku, PivotalTracker

%br
	.projectDescription
		%h3 Description
		%p For my Software Engineering course in Spring 2016, my group of 5 worked closely with the academic prep start-up Platina Education Group to develop their website. This was my first time working in a development environment and using git to develop with multiple team members. I lead weekly scrum meetings and assisted our client with thinking through the Platina product. Some of our features include: Login and Sign up, Authorization privileges (user/admin), blog posts, User database, and Image upload using Paperclip.
		%h3 Product
		%p Platina Education was founded by seasoned higher education practitioners who firmly believe in the value of international education and cross-cultural experience and growth because they themselves have benefitted from such opportunities. Partnering with high-quality educational entities in China and outstanding institutions of higher learning in the United States, Platina leverages its expertise and on-the-ground experiences in American higher education to serve as a bridge of opportunities for aspiring students from Greater China to access the rich educational resources in the United States. Platina’s services are intentionally integrative, comprising the three interconnected tracks of admissions and placement, education and learning, and advising and support.

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>

app/views/layouts/_sygn.html.haml
.projectsTop
	#carousel1.carousel.slide.carousel-fade{"data-ride" => "carousel"}
		%ol.carousel-indicators
			%li.active{"data-slide-to" => "0", "data-target" => "#carousel1"}
			%li{"data-slide-to" => "1", "data-target" => "#carousel1"}
			%li{"data-slide-to" => "2", "data-target" => "#carousel1"}
		.carousel-inner
			.active.item
				%img{:src => "assets/i2share.png", :id => "i2share_1"}
			.item
				%img{:src => "assets/createProject1.png", :id => "i2share_2"}
			.item
				%img{:src => "assets/myProfile.png", :id => "i2share_3"}
		%a.carousel-control.left{"data-slide" => "prev", :href => "#carousel1"} ‹
		%a.carousel-control.right{"data-slide" => "next", :href => "#carousel1"} ›
	.projectDetails
		%h1 i2share
		%h2 Project Sharing
		
		.projectTable
			%table
				%tr
					%td
						%b Role:
					%td
						%b Lead Front-end Developer
				%tr
					%td
						%b Website:
					%td
						%a{:href => "http://www.i2share.com", :target => "_blank"} www.i2share.com
						(not yet launched)
				%tr
					%td
						%b Status:
					%td Currently in production
				%tr
					%td
						%b Tools:
					%td Ruby on Rails, HTML/CSS, Javascript, Bootstrap, Vagrant, Chef, Git, Bitbucket
%br
	.projectDescription
		%b Description:
		dgtg
		%p 
			%b Product sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs
			sdfdfs

app/views/layouts/_tech4all1.html.haml
.projectsTop
	#carousel5.carousel.slide.carousel-fade{"data-ride" => "carousel"}
		%ol.carousel-indicators
			%li.active{"data-slide-to" => "0", "data-target" => "#carousel5"}
			%li{"data-slide-to" => "1", "data-target" => "#carousel5"}
			%li{"data-slide-to" => "2", "data-target" => "#carousel5"}
		.carousel-inner
			.active.item
				%img{:src => "assets/tech4all.png", :id => "tech4all_1"}
			.item
				%img{:src => "assets/tech4all2.png", :id => "tech4all_2"}
			.item
				%img{:src => "assets/tech4all3.png", :id => "tech4all_3"}
		%a.carousel-control.left{"data-slide" => "prev", :href => "#carousel5"} ‹
		%a.carousel-control.right{"data-slide" => "next", :href => "#carousel5"} ›
	.projectDetails
		%h1 Tech4All
		%h2 Mills College Hackathon
		
		.projectTable
			%table
				%tr
					%td
						%b Role:
					%td
						%b Co-Founder and Coordinator
				%tr
					%td
						%b Website:
					%td
						%a{:href => "http://www.millscc.herokuapp.com/hackathon", :target => "_blank"} www.millscc.herokuapp.com/hackathon
				%tr
					%td
						%b Status:
					%td Completed - Spring 2016
				%tr
					%td
						%b Tools:
					%td Google Drive, Trello, Photoshop, Canva, Heroku
%br
	.projectDescription
		%h3 Description
		%p My fellow classmate and I founded the first annual Mills College Tech4All hackathon. As Computer Science students at a liberal arts college, we were inspired to create a space that intertwines technology and interdisciplinary education to empower students to truly create solutions that address real-world problems. We assembled various committees and I was responsible for coordinator and planning, content writing, publicity, and graphic design. I helped with the hackathon conceptualization, planning, and execution. I also created the flyers and the hackathon descriptions and documentation.
		%h3 Product
		%p The theme of our hackathon is “Past. Present. Future.” The world is rapidly changing, and a lot of it is due to the fast-moving technology sector. The buzz word usually associated with tech is “disruption” -- but is “disruptive” necessarily “destructive”? We are living in a unique time, where we have a say in how we shape our future. The goal of our hackathon is to address and solve problems caused by a changing future coming into conflict with aspects of the past. What can we do to preserve the parts of our lives that are at risk of being lost? Instead of thinking about technology as disrupting our connection to the past, we invite you to find ways to use technology to address community issues, and honor our past while embracing the future.

app/views/layouts/_website1.html.haml
.projectsTop
	#carousel6.carousel.slide.carousel-fade{"data-ride" => "carousel"}
		%ol.carousel-indicators
			%li.active{"data-slide-to" => "0", "data-target" => "#carousel6"}
			%li{"data-slide-to" => "1", "data-target" => "#carousel6"}
			%li{"data-slide-to" => "2", "data-target" => "#carousel6"}
		.carousel-inner
			.active.item
				%img{:src => "assets/website1.png", :id => "website_1"}
			.item
				%img{:src => "assets/website2.png", :id => "website_2"}
			.item
				%img{:src => "assets/website3.png", :id => "website_3"}
		%a.carousel-control.left{"data-slide" => "prev", :href => "#carousel6"} ‹
		%a.carousel-control.right{"data-slide" => "next", :href => "#carousel6"} ›
	.projectDetails
		%h1 My Website
		%h2 Personal Web Resume
		
		.projectTable
			%table
				%tr
					%td
						%b Role:
					%td
						%b Developer
				%tr
					%td
						%b Website:
					%td
						%a{:href => "https://github.com/fhcheng/faye-website", :target => "_blank"} github.com/fhcheng/faye-website
				%tr
					%td
						%b Status:
					%td Completed - but always updating!
				%tr
					%td
						%b Tools:
					%td Ruby on Rails, HTML/CSS, Javascript, Bootstrap, Vagrant, Chef, Git
%br
	.projectDescription
		%h3 Description
		%p I wanted to create a personal website from scratch, and created this Rails App as a side project. I really enjoyed experimenting with javascript, further expanding my development skills, and modifying code elements to implement site features successfully. I also wanted to focus on creating a simple and elegant UX design.

		%h3 Product
		%p It is my hope that visitors to my site will be able to get a good idea of my programming and design skills, my personal experiences, and assess my potential as a Software Engineer and Product Manager.

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %title FC | Software Engineer
    <link rel='shortcut icon' href='favicon.ico' type='image/x-icon'/ >
    %script{:src => "assets/customjs.js", :type => "text/javascript"}
    %meta{:charset => "utf-8"}
      %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
        %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
          %meta{:content => "Website", :name => "description"}
            %meta{:content => "F.Cheng", :name => "author"}
              %link{:href => "../../favicon.ico", :rel => "icon"}
              %link{:href => "https://fonts.googleapis.com/css?family=Open+Sans:300", :rel => "stylesheet", :type => "text/css"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
  #container
    = render 'layouts/header'
    .container
      = yield
    = render 'layouts/footer'
    / Bootstrap core JavaScript ==================================================
    / Placed at the end of the document so the pages load faster
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"}
    / %= javascript_include_tag "bootstrap.min" %
    / script src="assets/bootstrap.min.js"></script

app/views/static_pages/about.html.haml
.about
	%h1 About
	%h3 Full-stack Software Engineer & Aspiring Product Manager.
	%p
	I'm a graduate student at Mills College studying Computer Science. I began as a Sociology major interested in entrepreneurship and business, who soon discovered her love for programming and creating new products. I am very passionate about mentorship and providing support for others. I am the
	%a{:href => "millscc.herokuapp.com/hackathon", :target => "_blank"}Tech4All Hackathon
	Co-Founder at my university, and the future Communities Chair for the 
	%a{:href => "http://anitaborg.org/", :target => "_blank"} Anita Borg Institute
	where I have an active role in promoting diversity in tech.
	%p
	%b What makes me different?
	I have a very diverse skillset that allows me to contribute to multiple facets of a project. In addition to being a programmer, I am a writer, artist, a meticulous organizer, product developer, public speaker, and a great team member. I love thinking through products, and learning the technologies to bring start-up ideas to life. I enjoy using my analytical abilities to come up with ideas and innovation solutions, and I pride myself in being creative and resourceful in tackling difficult challenges.
	%p
	I expect to graduate with a Master's degree in Computer Science in Fall 2016. If you'd like to learn more about me, I'd love to chat with you! 
	

app/views/static_pages/contact.html.haml
.contact
	%h1 Contact
	%p
	.col-md-12
		%img#sf{:src => "assets/background-1.png", :width => "100%", :height => "400px"}
	%h2 Faye Cheng
	%br
	%h4 fayehcheng(at)gmail.com

app/views/static_pages/designs.html.haml
.designs
	%h1 Designs
	%p
	.alert-message.alert-message-info
		%h4
			Design Samples
		%p
			For more information on the designs shown on this page, click on the desired image to
			= succeed "." do
				%strong display details
			%p
				%b#pTitle

	.designsPage
		%table{:align => "center", :style => "margin: 0px auto;", :style => "width:48%"}
			%tr
				%td
					%input#b1{:onclick => "changeTitle(this.value);", :type => "image", :src => "assets/1-1.png", :width => "140px", :height => "140px", :value => "Tiger Eye &mdash; (Illustrator and Sketchbook Pro)"}
				%td
					%input#b2{:onclick => "changeTitle(this.value);", :type => "image", :src => "assets/2-1.png", :width => "140px", :height => "140px", :value => "Pusheen &mdash; (Facebook, Sketchbook Pro)"}
				%td
					%input#b3{:onclick => "changeTitle(this.value);", :type => "image", :src => "assets/3-1.png", :width => "140px", :height => "140px", :value => "Tech4All Hackathon T-shirt Design &mdash; (CustomInk, Google Draw)"}
			%tr
				%td
					%input#b4{:onclick => "changeTitle(this.value);", :type => "image", :src => "assets/4-1.png", :width => "140px", :height => "140px", :value => "Native American Women in Computing Logo"}
				%td
					%input#b5{:onclick => "changeTitle(this.value);", :type => "image", :src => "assets/5-1.png", :width => "140px", :height => "140px", :value => "Lion &mdash; (Colored Pencils)"}
				%td
					%input#b6{:onclick => "changeTitle(this.value);", :type => "image", :src => "assets/tech4all.png", :width => "140px", :height => "140px", :value => "Tech4All Hackathon Logo &mdash; (Photoshop)"}
			%tr
				%td
					%input#b7{:onclick => "changeTitle(this.value);", :type => "image", :src => "assets/7-1.png", :width => "140px", :height => "140px", :value => "NextList Android App Design &mdash; (Illustrator, Sketchbook Pro)"}
				%td	
					%input#b8{:onclick => "changeTitle(this.value);", :type => "image", :src => "assets/8-1.png", :width => "140px", :height => "140px", :value => "PinkThink Hackathon &mdash; (Sketchbook Pro, Photoshop)"}
				%td
					%input#b9{:onclick => "changeTitle(this.value);", :type => "image", :src => "assets/9-1.png", :width => "140px", :height => "140px", :value => "Tiger &mdash; (Colored Pencils)"}

app/views/static_pages/faq.html.haml
<h1>StaticPages#faq</h1>
<p>Find me in app/views/static_pages/faq.html.erb</p>

app/views/static_pages/index.html.haml
%body#home
	.homeDiv.center
		%img{:src => "assets/images/self-bw-1.png", :id => "self"}
		.homeDivHeader
			%h1 FAYE CHENG
			%hr.homeHR
			.homeDivText	
				.headerText
					%b Hi there, I'm Faye.
					%p Web Developer, UX Designer, and Sociologist turned Software Engineer.
					%p
					%a{:href => about_path}
						#learnMore
							.back
								.button_base.b05_3d_roll
									%div ENTER SITE
									%div ENTER SITE

		%link{:href => "//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css", :rel => "stylesheet"}
		.homeLinks
			.text-left.left-block
				%a{:href => "https://www.linkedin.com/in/fayehcheng", :target => "_blank"}
					%i.fa.fa-linkedin-square.fa-3x.social
				%a{:href => "https://github.com/fhcheng", :target => "_blank"}
					%i.fa.fa-github-square.fa-3x.social
				%a{:href => "https://bitbucket.org/fhcheng/", :target => "_blank"}
					%i.fa.fa-bitbucket-square.fa-3x.social
				%a{:href => "https://twitter.com/fayehcheng", :target => "_blank"}
					%i.fa.fa-twitter-square.fa-3x.social
				%a{:href => "mailto:fayehcheng@gmail.com", :target => "_blank"}
					%i.fa.fa-envelope-square.fa-3x.social

app/views/static_pages/resume.html.haml
.resumePage
	%h1 Resume
	%img{:src => "assets/resume1.png", :id => "resume1"}
	%img{:src => "assets/resume4.png", :id => "resume4"}
	%img{:src => "assets/resume2.png", :id => "resume2"}
	%img{:src => "assets/resume3.png", :id => "resume3"}
	%p
	%form{:action => "FayeCheng_Resume.pdf", :method => "get", :target => "_blank"}
		%button{:type => "submit", :class => "btn btn-info"} Download Resume

%br
%br
%br
%br
%br
%br
%br
%br

	